name: Test Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-id: push
