name: Test and Nightly Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      build-id: push

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Parse Forgejo payload
        shell: bash
        run: |
          export PAYLOAD_JSON='${{ toJSON(github.event.client_payload) }}'
          export FORGEJO_TOKEN=${{ secrets.FORGEJO_TOKEN }}
          ./.ci/parse.sh master

      - name: Set environment variables
        run: |
          echo "REPO=QDash-CI/Test" >> $GITHUB_ENV
          echo "DEVEL=true" >> $GITHUB_ENV

      - name: Package artifacts nicely
        run: |
          export ID=continuous
          ./.ci/pack.sh

      - name: Generate changelog
        run: |
          ./.ci/changelog/test.sh > changelog.md

      - name: Delete Previous Release
        run: |
          gh release delete "continuous" --repo "$REPO" --cleanup-tag  -y
          sleep 5
        env:
          GH_TOKEN: "${{ secrets.CUSTOM_GITHUB_TOKEN }}"
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "QDash - Continuous Build"
          tag_name: continuous
          repository: ${{ env.REPO }}
          body_path: ./changelog.md
          prerelease: false
          draft: false
          generate_release_notes: false
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          make_latest: true
          files: |
            artifacts/*
